blank_issues_enabled: false
contact_links:
  - name: Help & Support
    url: https://github.com/{username}/{repo}/discussions/new?category=help
    about: 'Ask questions and get help in our discussion forums.'
